opensafely/post-covid-neurodegenerative

analysis/descriptives/table2.R, analysis/utility.R, project.yaml
Updated table 2 script.
Utility script added.
=> Table 2 script

analysis/create_project_actions.R, analysis/descriptives/table2.R, analysis/descriptives/venn.R, analysis/table1.R, project.yaml
Added table 1 script. Table 2 and Venn diagrams scripts have been updated.
=> Scripts updates

analysis/create_project_actions.R, analysis/descriptives/table1.R, analysis/figure/format_table1.R, analysis/figure/format_table2.R, analysis/model/make_model_input.R, analysis/preprocess/preprocess_data.R, project.yaml
Table 1 script updated.
Preprocess script update.
Format table1 and table2 scripts updated.
=> Update format tables

analysis/preprocess/preprocess_data.R
Fix columns in the preprocess, changes were made after comparing with GI.
Stage1 seems to be fine after comparing with GI.
=> Fix columns

analysis/preprocess/preprocess_data.R
Removed describe cohort lines to run the preprocess script on the server.
=> Removed lines

analysis/preprocess/Stage1_data_cleaning.R
=> Fix input name

analysis/create_project_actions.R, analysis/preprocess/Stage1_data_cleaning.R, project.yaml
Consort dataframe added to stage1 and project actions.
=> Added consort to stage1

analysis/create_project_actions.R, analysis/model/make_other_output.R, project.yaml
=> Consort output

analysis/descriptives/venn.R
Fix column names for Alzheimer, Parkinson, and Cognitive impairment. Any dementia source contributions modified.
=> Updated venn script

analysis/create_project_actions.R, analysis/descriptives/extendedtable1.R, analysis/utility.R, project.yaml
Extended table 1 script added, and updated utility script.
=> Added extended table 1

.gitignore, analysis/figure/figure1.R, analysis/figure/figure2.R, analysis/figure/format_table1.R, analysis/figure/format_table2.R, analysis/post_release/fn-lifetable.R, analysis/post_release/lifetables_compiled.R, analysis/post_release/manuscript_extendedtable1.R, analysis/post_release/manuscript_figureAER.R, analysis/post_release/manuscript_figureAdj.R, analysis/post_release/manuscript_figureMain.R, analysis/post_release/manuscript_table1.R, analysis/post_release/manuscript_table2.R, analysis/post_release/manuscript_table3.R, analysis/post_release/manuscript_tableAER.R, analysis/post_release/manuscript_tableConsort.R, analysis/post_release/run_post_release.R, analysis/post_release/specify_paths.R, analysis/post_release/specify_paths_example.R, lib/plot_labels.csv
=> Post-release

analysis/model/make_model_input.R
Missing line for migraine models (make_model_input).
=> Missing line

analysis/common_variables.py, analysis/prelim.R, analysis/preprocess/Stage1_data_cleaning.R, analysis/preprocess/preprocess_data.R, analysis/study_definition_prelim.py
Removed deregistration date in the common_variables. 
Updated prelim info with deregistration date.
Added death date and deregistration date in preprocess. 
Updated active registration in stage1.
Updated codelists.
=> Deregistration update

analysis/create_project_actions.R, analysis/preprocess/Stage1_data_cleaning.R, analysis/preprocess/preprocess_data.R, project.yaml
Remove repeated lines (prelim_data) in the preprocess script. Remove objects after being saved (following OS documentation).
=> Updating death and deregistration

analysis/preprocess/preprocess_data.R
Remove repeated "inne_join" line.
=> Remove repeated line

analysis/create_project_actions.R, project.yaml
Update model output (create_project_actions) to extract models of interest.
=> Main models output

analysis/create_project_actions.R, analysis/model/make_model_output.R, project.yaml
Added threshold and utility to model_output script. Output redaction updated.
=> Update model output script

analysis/create_project_actions.R, analysis/median_iqr_age.R, analysis/stata/cox_model.do, analysis/stata/extra_ados/estadd.ado, analysis/stata/extra_ados/estadd.hlp, analysis/stata/extra_ados/estout.ado, analysis/stata/extra_ados/estout.hlp, analysis/stata/extra_ados/estpost.ado, analysis/stata/extra_ados/estpost.hlp, analysis/stata/extra_ados/eststo.ado, analysis/stata/extra_ados/eststo.hlp, analysis/stata/extra_ados/esttab.ado, analysis/stata/extra_ados/esttab.hlp, analysis/stata/make_stata_model_output.R, lib/plot_labels.csv, project.yaml
Prepared scripts for Stata models.
Models to be run using Stata needs to be updated
To test the models use test prevax-vascular-dementia.
Lines 81-85 removed (exclusive to gastro repo).
=> Stata models

analysis/create_project_actions.R, project.yaml
Remove failed models from model output.
=> Remove failed models

analysis/create_project_actions.R, analysis/dataset_clean/fn-preprocess.R, project.yaml
I checked that it produced an identical venn output as before, and that it didn't change the output of dataset_clean.
=> Re add venn

analysis/dataset_clean/fn-qa.R
Replace `lcd_date` with today's date in QA conditions for implausible births and deaths
=> Replace lcd_date with today's date
